#!/usr/bin/env bash
# codex_second_opinion.sh -- Codex as a second opinion for this repo (copied from aurora_monitor).
#
# Fable (Claude Code) stays leading: every Codex finding is a hypothesis until
# it is verified against file and line. No git gate, no obligation per PR.
# Codex runs read-only and never edits the working tree.
#
# Usage:
#   scripts/codex_second_opinion.sh plan   <path/to/plan.md> ["extra question"]
#   scripts/codex_second_opinion.sh review [--base <ref> | --uncommitted | --commit <sha>]
#                                          (default: --base origin/main)
#   scripts/codex_second_opinion.sh ask    "<question: state what you believe and what you rejected>"
#   scripts/codex_second_opinion.sh audit  <path/to/prompt.md>   (prompt file verbatim, e.g. docs/refs/codex-review-prompt.md)
#
# Env:  CODEX_MODEL  (default gpt-5.6-sol)
#       CODEX_EFFORT (default xhigh; low|medium|high|xhigh|max|ultra)
# Out:  logs/codex/<YYYYMMDD-HHMMSS>-<pid>-<mode>.md  (final answer)
#       logs/codex/<YYYYMMDD-HHMMSS>-<pid>-<mode>.stream.log  (raw stream)
#       Both gitignored. A failed run writes no .md, so never reuse an older log.
# Note: a run at max effort takes 25-66 minutes. Start those from a terminal
#       (nohup ... &), not from a Claude Bash call, which caps at 10 minutes.
# Never put secrets, tokens or user data in a prompt. Paths and code are fine.
# Do not edit this file while a run is active: bash reads it incrementally.
set -euo pipefail

MODE="${1:-}"
[ -n "$MODE" ] || { sed -n '2,22p' "$0"; exit 2; }
shift

command -v codex >/dev/null 2>&1 || { echo "codex CLI not found (npm i -g @openai/codex)" >&2; exit 1; }
codex login status 2>&1 | grep -q "Logged in" || { echo "codex is not logged in: run 'codex login'" >&2; exit 1; }

REPO_ROOT=$(git rev-parse --show-toplevel)
LOG_DIR="$REPO_ROOT/logs/codex"
mkdir -p "$LOG_DIR"
STAMP=$(date +%Y%m%d-%H%M%S)
OUT="$LOG_DIR/$STAMP-$$-$MODE.md"
STREAM="${OUT%.md}.stream.log"

MODEL="${CODEX_MODEL:-gpt-5.6-sol}"
EFFORT="${CODEX_EFFORT:-xhigh}"
# `codex exec` takes -C/-m/-s; `codex review` only takes -c overrides, so the
# review branch sets the same things through config keys and a cd.
COMMON=(-C "$REPO_ROOT" -m "$MODEL" -c "model_reasoning_effort=\"$EFFORT\"" -s read-only)
REVIEW_CFG=(-c "model=\"$MODEL\"" -c "model_reasoning_effort=\"$EFFORT\"" -c 'sandbox_mode="read-only"')

# Refuse the obvious secret shapes before anything leaves the machine.
refuse_secrets() {
  if printf '%s' "$1" | grep -Eq 'sk-[A-Za-z0-9]{16,}|AKIA[0-9A-Z]{16}|BEGIN (RSA |EC )?PRIVATE KEY|eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}'; then
    echo "prompt looks like it contains a secret; refusing" >&2
    exit 1
  fi
}

FORMAT='For every finding give file path, line number, a short quote, a concrete failure scenario and a severity (P1 blocks, P2 should fix, P3 nit), ranked by severity. Findings only, no rewrites. If it holds up, say "no findings above P3" instead of inventing issues.'

echo "codex $MODE  model=$MODEL effort=$EFFORT" >&2
echo "stream: ${STREAM#"$REPO_ROOT/"}" >&2
START=$(date +%s)

case "$MODE" in
  review)
    # Selector flags pass straight through to `codex review`.
    [ $# -gt 0 ] || set -- --base origin/main
    (cd "$REPO_ROOT" && codex review "${REVIEW_CFG[@]}" "$@" 2>&1 | tee "$STREAM" >/dev/null) || true
    # `codex review` has no output flag: cut the text after the last "codex"
    # marker line out of the stream. That used to be an awk one-liner here;
    # it now lives in a tested script because the CLI started COLOURING that
    # marker on 2026-09-10 and twelve reports in a row were written empty
    # while the wrapper still said "saved".
    python3 "$REPO_ROOT/scripts/codex_extract_report.py" "$STREAM" > "$OUT" || true
    ;;
  plan)
    PLAN="${1:-}"
    [ -n "$PLAN" ] && [ -f "$REPO_ROOT/$PLAN" ] || { echo "plan file not found: '$PLAN' (path relative to repo root)" >&2; exit 2; }
    EXTRA="${2:-}"
    refuse_secrets "$EXTRA"
    PROMPT="Read the plan at $PLAN and the code it references. We believe this plan is sound; break it. List wrong assumptions, missing steps or layers, risks, and what a careful reviewer would ask before approving. $FORMAT"
    [ -n "$EXTRA" ] && PROMPT="$PROMPT Specific question: $EXTRA"
    codex exec "${COMMON[@]}" -o "$OUT" "$PROMPT" </dev/null 2>&1 | tee "$STREAM" >/dev/null || true
    ;;
  ask)
    QUESTION="${1:-}"
    [ -n "$QUESTION" ] || { echo "ask needs a question" >&2; exit 2; }
    refuse_secrets "$QUESTION"
    PROMPT="Second opinion requested on a decision in this repository. Give your independent judgement first, then what you would verify in the code, with file and line. Do not just confirm; say where the reasoning is weak. Question: $QUESTION"
    codex exec "${COMMON[@]}" -o "$OUT" "$PROMPT" </dev/null 2>&1 | tee "$STREAM" >/dev/null || true
    ;;
  audit)
    # Full-app audit: the prompt file IS the prompt (no second-opinion
    # framing); the file carries its own output format. Run at max effort.
    FILE="${1:-}"
    [ -n "$FILE" ] && [ -f "$REPO_ROOT/$FILE" ] || { echo "prompt file not found: '$FILE' (path relative to repo root)" >&2; exit 2; }
    PROMPT="$(cat "$REPO_ROOT/$FILE")"
    refuse_secrets "$PROMPT"
    codex exec "${COMMON[@]}" -o "$OUT" "$PROMPT" </dev/null 2>&1 | tee "$STREAM" >/dev/null || true
    ;;
  *)
    echo "unknown mode '$MODE' (plan|review|ask|audit)" >&2; exit 2 ;;
esac

ELAPSED=$(( $(date +%s) - START ))
# Blank counts as failed: an empty report used to pass this check on a single
# newline, which is how the broken extraction stayed invisible for a day.
if ! grep -q '[^[:space:]]' "$OUT" 2>/dev/null; then
  rm -f "$OUT"
  echo "FAILED after ${ELAPSED}s: no answer written. See ${STREAM#"$REPO_ROOT/"}" >&2
  exit 1
fi
echo "saved: ${OUT#"$REPO_ROOT/"} (${ELAPSED}s)" >&2
